DELETE FROM CONTA;
DELETE FROM SALARIO_FINAL;
DELETE FROM DIA_TRABALHO;
DELETE FROM FUNCIONARIOS_OBRAS;
DELETE FROM OBRA;
DELETE FROM FUNCIONARIO;
DELETE FROM MERCADO;
DELETE FROM CATEGORIAS_PROFISSIONAIS;