DROP TABLE IF EXISTS INTERVALO_MERCADO;
DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS SALARIO_FINAL;
DROP TABLE IF EXISTS DIA_TRABALHO;
DROP TABLE IF EXISTS FUNCIONARIOS_OBRAS;
DROP TABLE IF EXISTS OBRA;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CATEGORIAS_PROFISSIONAIS;